volumes:
  - name: 'cypress-cache'
    path: '/root/.cache'

steps:
  # Clone the repository
  - name: 'gcr.io/cloud-builders/git'
    args: ['clone', '${_REPO_URL}', '--branch', '${_BRANCH}', '.']

  # Install dependencies
  - name: 'node:20'
    args: ['npm', 'ci']

  # Get secrets from Secret Manager
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud secrets versions access latest --secret=cypress-environment-variables > cypress.env.json

  # Make scripts executable
  - name: 'debian:stable-slim'
    args: ['chmod', '+x', 'run-cypress.sh', 'run-parallel.sh']

  # Install Cypress once
  - name: 'cypress/included:14.3.0'
    id: 'install-cypress'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        cypress install
        cypress verify
        echo "Cypress binary installed successfully"
    volumes:
      - name: 'cypress-cache'
        path: '/root/.cache'

  # Run parallel tests using the script
  - name: 'cypress/included:14.3.0'
    entrypoint: './run-parallel.sh'
    args: ['${_ENV}', '${_SPECS}', '${_TOTAL_CONTAINERS}', '${BUILD_ID}', '${_CYPRESS_RECORD_KEY}', '${_TAGS}']
    env:
      - 'CI_PLATFORM=gcp'
      - 'CI_SERVICE=cloud-build'
      - 'TOTAL_CONTAINERS=${_TOTAL_CONTAINERS}'
      - 'PERCY_TOKEN=${_PERCY_TOKEN}'
      - 'PROJECT_TOKEN=${_PROJECT_TOKEN}'
      - 'CYPRESS_excludeSpecPattern=**/smart-ui-tests/**'
      - 'CYPRESS_grepOmitFiltered=true'
    volumes:
      - name: 'cypress-cache'
        path: '/root/.cache'

  # Upload results to GCS
  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['-m', 'cp', '-r', 'cypress/results/json', 'gs://cypress-example-e2e-results/${BUILD_ID}/cypress/results/']

substitutions:
  _ENV: 'production'  # Default environment
  _SPECS: 'all'       # Default specs to run
  _TOTAL_CONTAINERS: '2'  # Default total containers, will be overridden by GitHub Actions
  _REPO_URL: 'https://github.com/bhargav-garlapati/cypress-example-e2e.git'  # Default repo URL
  _BRANCH: 'main'  # Default branch
  _CYPRESS_RECORD_KEY: ''  # Default empty value, will be overridden by GitHub Actions
  _TAGS: ''  # Default empty value for tags
  _PERCY_TOKEN: ''  # Default empty value for Percy token
  _PROJECT_TOKEN: ''  # Default empty value for SmartUI token

timeout: 1800s  # 30 minutes
