name: Cypress Tests on GCP

on:
  # Manual trigger only
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run tests against'
        required: true
        default: 'production'
        type: choice
        options:
          - production
          - staging
      specs:
        description: 'Test specs to run (comma-separated or "all")'
        required: true
        default: 'all'
        type: string
      tags:
        description: 'Tags to filter tests (comma-separated)'
        required: false
        default: ''
        type: string

jobs:
  trigger-gcp-tests:
    name: Trigger GCP Cloud Build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        containers: [1, 2]  # Using 2 containers for parallelization
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Google Cloud SDK
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
          export_environment_variables: true
          
      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: cypress-example-e2e-397816

      - name: Trigger Cloud Build
        id: cloud-build
        run: |
          BUILD_ID=$(gcloud builds submit --config=cloudbuild.yaml \
            --no-source \
            --substitutions=_ENV=${{ github.event.inputs.environment }},_SPECS=${{ github.event.inputs.specs }},_CONTAINER_IDX=${{ matrix.containers }},_TOTAL_CONTAINERS=${{ strategy.job-total }},_REPO_URL="${{ github.server_url }}/${{ github.repository }}.git",_BRANCH="${{ github.ref_name }}",_CYPRESS_RECORD_KEY="${{ secrets.CYPRESS_RECORD_KEY }}",_TAGS="${{ github.event.inputs.tags }}",_PERCY_TOKEN="${{ secrets.PERCY_TOKEN }}",_PROJECT_TOKEN="${{ secrets.PROJECT_TOKEN }}" \
            --async --format='value(id)')
          echo "build_id=$BUILD_ID" >> $GITHUB_OUTPUT
          echo "Triggered Cloud Build with ID: $BUILD_ID"

      - name: Wait for Cloud Build to complete
        run: |
          gcloud beta builds log --stream ${{ steps.cloud-build.outputs.build_id }}

      - name: Download test results from GCS
        id: download-gcs
        continue-on-error: true
        run: |
          mkdir -p cypress/results/json
          gsutil -m cp -r gs://cypress-example-e2e-results/${{ steps.cloud-build.outputs.build_id }}/* ./ || echo "No results found in GCS bucket"
          echo "GCS downloaded content:"
          find cypress/results -type f | sort

      - name: Save results folder
        uses: actions/upload-artifact@v4
        with:
          name: cypress-results-${{ matrix.containers }}
          path: cypress/results/json

  post-tests-results:
    runs-on: ubuntu-latest
    needs: trigger-gcp-tests
    if: ${{ always() }}
    steps: 
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Download all artifacts
        id: download
        continue-on-error: true
        uses: actions/download-artifact@v4
        with:
          path: downloaded-artifacts

      - name: Debug downloaded artifacts
        run: |
          echo "Downloaded artifacts structure:"
          find downloaded-artifacts -type f | sort

      - name: Prepare results directory
        run: |
          mkdir -p cypress/results/json
          find downloaded-artifacts -name "*.json" -exec cp {} cypress/results/json/ \; || echo "No JSON files found"
          echo "Contents of cypress/results/json:"
          ls -la cypress/results/json || echo "Directory is empty"
  
      - name: Create public directory
        run: mkdir -p public

      - name: Merge test results into one
        run: npm run report:merge || echo "No test results to merge"

      - name: Generate HTML report
        run: npm run report:generate || echo "No report to generate"

      - name: Create default report if no results
        if: ${{ failure() }}
        run: |
          echo "<html><body><h1>No test results available</h1><p>No test results were generated in this run.</p></body></html>" > public/index.html

      - name: Deploy report page
        if: ${{ always() }}
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          user_name: "github-actions[bot]"
          user_email: "github-actions[bot]@users.noreply.github.com"
