name: Cypress Tests on GH Actions
# This workflow will run Cypress tests on GitHub Actions
on:
  # Manual trigger only
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run tests against'
        required: true
        default: 'production'
        type: choice
        options:
          - production
          - staging
      specs:
        description: 'Test specs to run (comma-separated or "all")'
        required: true
        default: 'all'
        type: string
      tags:
        description: 'Tags to filter tests (comma-separated)'
        required: false
        default: ''
        type: string

jobs:
  cypress-tests:
    name: E2E Test Run
    # timeout-minutes: 15
    runs-on: ubuntu-22.04
    container:
      image: cypress/browsers:latest
      options: --user 1001
    strategy:
      # when one test fails, DO NOT cancel the other
      # containers, because this will kill Cypress processes
      # leaving the Dashboard hanging ...
      fail-fast: false
      matrix:
        # run copies of the current job in parallel
        containers: [1, 2]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install project
        run: |
          npm ci

      - name: Cypress info
        run: npx cypress info

      - name: Node info
        run: node -v

      - name: Make script executable
        run: chmod +x run-cypress.sh

      - name: Run Cypress Tests
        run: >
          CI_PLATFORM=github CI_SERVICE=actions ./run-cypress.sh
          ${{ github.event.inputs.environment || 'production' }}
          ${{ github.event.inputs.specs || 'all' }}
          ${{ matrix.containers }}
          ${{ github.run_id }}-${{ github.run_attempt }}
          ${{ secrets.CYPRESS_RECORD_KEY }}
          ${{ github.event.inputs.tags || '' }}
        env:
          ENV: ${{ github.event.inputs.environment || 'production' }}
          CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
          PROJECT_TOKEN: ${{ secrets.PROJECT_TOKEN }}

      - name: Save results folder
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: my-artifact-${{ matrix.containers }}
          path: |
            cypress/results
            cypress.config.js
            package.json
            reporter-config.json

  post-tests-results:
    runs-on: ubuntu-latest
    # container:
    #   image: cypress/browsers:node16.13.0-chrome95-ff94
    #   options: --user 1001
    needs: cypress-tests
    if: ${{ always() }}
    steps: 
     - name: Download the results folders
       uses: actions/download-artifact@v4
       with:
          name: my-artifact-*
          merge-multiple: true

     - name: Test Artifact download
       run: ls -R
  
    #  - name: Creating a public directory and setting permissions
    #    if: ${{ always() }}
    #    run: |
    #       mkdir public
    #       cp -r cypress/videos public/videos

     - name: Merge test results into one
       if: ${{ always() }}
       run: npm run report:merge

     - name: Generate HTML report
       if: ${{ always() }}
       run: npm run report:generate

     - name: Deploy report page
       if: ${{ always() }}
       uses: peaceiris/actions-gh-pages@v4
       with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          user_name: "github-actions[bot]"
          user_email: "github-actions[bot]@users.noreply.github.com"
          
    #  - name: "Cypress Email Results"
    #    uses: cypress-io/github-action@v4
    #    with:
    #       runTests: false
    #       config-file: email.config.js
    #    env:
    #       # email test results after the tests are finished
    #       EMAIL_TO: ${{ secrets.EMAIL_TO }}
    #       # pass SendGrid settings to the plugin via environment variables
    #       SENDGRID_HOST: ${{ secrets.SENDGRID_HOST }}
    #       SENDGRID_PORT: ${{ secrets.SENDGRID_PORT }}
    #       SENDGRID_USER: ${{ secrets.SENDGRID_USER }}
    #       SENDGRID_PASSWORD: ${{ secrets.SENDGRID_PASSWORD }}
    #       SENDGRID_FROM: ${{ secrets.SENDGRID_FROM }}
          
    #  - name: Post Slack Notification
    #    uses: 8398a7/action-slack@v3
    #    with:
    #       username: "CYPRESS-E2E-REPORT"
    #       status: custom
    #       fields: workflow,message,commit,repo,ref,author
    #       custom_payload: |
    #         {
    #           attachments: [{
    #             color: '${{ job.status }}' === 'success' ? 'good' : '${{ job.status }}' === 'failure' ? 'danger' : 'warning',
    #             text: `${process.env.AS_WORKFLOW}\n (${process.env.AS_MESSAGE})-(${process.env.AS_COMMIT}) of ${process.env.AS_REPO}@${process.env.AS_REF} by ${process.env.AS_AUTHOR} ${{ job.status }}`,
    #           }]
    #         }
    #    env:
    #       SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
    #    if: always() # Pick up events even if the job fails or is cancelled.
